runtime: python310

env_variables:
  SECRET_KEY: "your-secret-key-here-change-this-in-production"
  
automatic_scaling:
  min_instances: 0
  max_instances: 2

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
  
instance_class: F1 